import 'package:flutter/material.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedIcons8chatmessage483Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedVectorWidget39.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedEllipse11Widget3.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedMSDhoneWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/Generated26minagoWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedEllipse11Widget4.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedEllipse11Widget2.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedSearchAnythingWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedRectangle602Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedArunKumarWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedAndroidStatusBarsWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedEllipse11Widget1.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedEllipse13Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedSentShortsVideoNowWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/Generated26minagoWidget2.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedUserUsers_GroupWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedGaneshWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedLogoWidget1.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedGivemeavengersWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedGroupsWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedThanosWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/Generated2dsWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedSearchWidget1.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedAllWidget1.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/Generated26minagoWidget1.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedWatchMrBeastVideoWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedCallsWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedChatsWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedRectangle601Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedLine1Widget1.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall3widget/generated/GeneratedSendmethedetailsnowWidget.dart';

/* Frame Android Small - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(33.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(33.0),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(33.0),
            child: Container(
              color: Color.fromARGB(255, 0, 0, 0),
            ),
          ),
          Positioned(
            left: -1.0,
            top: -4.0,
            right: null,
            bottom: null,
            width: 358.23809814453125,
            height: 33.00341796875,
            child: GeneratedAndroidStatusBarsWidget1(),
          ),
          Positioned(
            left: 9.0,
            top: 34.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 26.99999237060547,
            child: GeneratedLogoWidget1(),
          ),
          Positioned(
            left: 327.0,
            top: 36.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedEllipse1Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.04446873664855957;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 16.008745193481445;

              double percentHeight = 0.031240051984786986;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 19.993633270263672;

              return Stack(children: [
                TransformHelper.translateAndScale(
                    translateX: constraints.maxWidth * 0.25,
                    translateY: constraints.maxHeight * 0.9125,
                    translateZ: 0,
                    scaleX: scaleX,
                    scaleY: scaleY,
                    scaleZ: 1,
                    child: GeneratedVectorWidget39())
              ]);
            }),
          ),
          Positioned(
            left: 7.0,
            top: 579.0,
            right: null,
            bottom: null,
            width: 327.0,
            height: 44.0,
            child: GeneratedGroup4Widget1(),
          ),
          Positioned(
            left: 288.0,
            top: 640.0,
            right: null,
            bottom: null,
            width: 50.0,
            height: 3.0,
            child: GeneratedLine1Widget1(),
          ),
          Positioned(
            left: 29.0,
            top: 135.0,
            right: null,
            bottom: null,
            width: 97.0,
            height: 0.0,
            child: GeneratedLine2Widget(),
          ),
          Positioned(
            left: 23.0,
            top: 76.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 20.0,
            child: GeneratedAllWidget1(),
          ),
          Positioned(
            left: 304.0,
            top: 579.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 28.0,
            child: GeneratedIcons8chatmessage483Widget(),
          ),
          Positioned(
            left: 105.0,
            top: 33.0,
            right: null,
            bottom: null,
            width: 207.0,
            height: 28.0,
            child: GeneratedRectangle601Widget(),
          ),
          Positioned(
            left: 274.0,
            top: 33.0,
            right: null,
            bottom: null,
            width: 28.0,
            height: 28.0,
            child: GeneratedSearchWidget1(),
          ),
          Positioned(
            left: 132.0,
            top: 39.0,
            right: null,
            bottom: null,
            width: 110.0,
            height: 18.0,
            child: GeneratedSearchAnythingWidget(),
          ),
          Positioned(
            left: 7.0,
            top: 167.0,
            right: null,
            bottom: null,
            width: 63.0,
            height: 59.0,
            child: GeneratedEllipse11Widget1(),
          ),
          Positioned(
            left: 7.0,
            top: 261.0,
            right: null,
            bottom: null,
            width: 63.0,
            height: 59.0,
            child: GeneratedEllipse11Widget2(),
          ),
          Positioned(
            left: 7.0,
            top: 367.0,
            right: null,
            bottom: null,
            width: 63.0,
            height: 59.0,
            child: GeneratedEllipse11Widget3(),
          ),
          Positioned(
            left: 7.0,
            top: 461.0,
            right: null,
            bottom: null,
            width: 63.0,
            height: 59.0,
            child: GeneratedEllipse11Widget4(),
          ),
          Positioned(
            left: -18.0,
            top: 65.0,
            right: null,
            bottom: null,
            width: 394.0,
            height: 66.0,
            child: GeneratedRectangle602Widget(),
          ),
          Positioned(
            left: 59.0,
            top: 106.0,
            right: null,
            bottom: null,
            width: 44.0,
            height: 21.0,
            child: GeneratedChatsWidget(),
          ),
          Positioned(
            left: 44.0,
            top: 130.0,
            right: null,
            bottom: null,
            width: 82.0,
            height: 1.0,
            child: GeneratedLine3Widget(),
          ),
          Positioned(
            left: 178.0,
            top: 110.0,
            right: null,
            bottom: null,
            width: 41.0,
            height: 24.0,
            child: GeneratedCallsWidget(),
          ),
          Positioned(
            left: 270.0,
            top: 108.0,
            right: null,
            bottom: null,
            width: 57.0,
            height: 24.0,
            child: GeneratedGroupsWidget(),
          ),
          Positioned(
            left: 48.0,
            top: 215.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 11.0,
            child: GeneratedEllipse12Widget(),
          ),
          Positioned(
            left: 56.0,
            top: 408.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 11.0,
            child: GeneratedEllipse13Widget(),
          ),
          Positioned(
            left: 82.0,
            top: 167.0,
            right: null,
            bottom: null,
            width: 123.0,
            height: 26.0,
            child: GeneratedArunKumarWidget(),
          ),
          Positioned(
            left: 82.0,
            top: 261.0,
            right: null,
            bottom: null,
            width: 85.0,
            height: 26.0,
            child: GeneratedGaneshWidget(),
          ),
          Positioned(
            left: 82.0,
            top: 373.0,
            right: null,
            bottom: null,
            width: 119.0,
            height: 26.0,
            child: GeneratedMSDhoneWidget(),
          ),
          Positioned(
            left: 83.0,
            top: 461.0,
            right: null,
            bottom: null,
            width: 83.0,
            height: 26.0,
            child: GeneratedThanosWidget(),
          ),
          Positioned(
            left: 318.0,
            top: 191.0,
            right: null,
            bottom: null,
            width: 27.0,
            height: 23.0,
            child: Generated2dsWidget(),
          ),
          Positioned(
            left: 288.0,
            top: 285.0,
            right: null,
            bottom: null,
            width: 70.0,
            height: 20.0,
            child: Generated26minagoWidget(),
          ),
          Positioned(
            left: 287.0,
            top: 405.0,
            right: null,
            bottom: null,
            width: 70.0,
            height: 20.0,
            child: Generated26minagoWidget1(),
          ),
          Positioned(
            left: 288.0,
            top: 492.0,
            right: null,
            bottom: null,
            width: 70.0,
            height: 20.0,
            child: Generated26minagoWidget2(),
          ),
          Positioned(
            left: -0.025931252166628838,
            top: 164.0341796875,
            right: null,
            bottom: null,
            width: 355.0506896972656,
            height: 1.0,
            child: GeneratedLine4Widget(),
          ),
          Positioned(
            left: 60.0,
            top: 488.0,
            right: null,
            bottom: null,
            width: 212.0,
            height: 26.0,
            child: GeneratedGivemeavengersWidget(),
          ),
          Positioned(
            left: 82.0,
            top: 188.0,
            right: null,
            bottom: null,
            width: 212.0,
            height: 26.0,
            child: GeneratedSendmethedetailsnowWidget(),
          ),
          Positioned(
            left: 78.0,
            top: 282.0,
            right: null,
            bottom: null,
            width: 188.0,
            height: 26.0,
            child: GeneratedSentShortsVideoNowWidget(),
          ),
          Positioned(
            left: 75.0,
            top: 400.0,
            right: null,
            bottom: null,
            width: 203.0,
            height: 18.0,
            child: GeneratedWatchMrBeastVideoWidget(),
          ),
          Positioned(
            left: 324.0,
            top: 105.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedUserUsers_GroupWidget(),
          )
        ]),
      ),
    ));
  }
}
