import 'package:flutter/material.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedTransformers2023HDTrailerInTamilWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedCastWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedNotifications_noneWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedMore_vertWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedPSGStatusWidget1.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/Generated33mViewsWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/Generated22023Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedGamingWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedYoutubeshortsWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedMrBeastWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedRectangle599Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedRectangle585Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedWatchLaterWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedVectorWidget15.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedLogoWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/Generated12MViews2hoursagoWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedMore_vertWidget2.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedRectangle596Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/Generated55MviewsWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedRectangle598Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedUIUXWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedRectangle596Widget3.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedPSGStatusWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedTodayWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedRectangle600Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedRectangle596Widget2.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedMore_vertWidget1.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedRectangle597Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedAllWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedRectangle596Widget4.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/Generated55MviewsWidget1.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedIcons8chatmessage481Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedRectangle596Widget1.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedViratKohliStatusWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedRectangle596Widget5.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedRectangle584Widget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedAndroidStatusBarsWidget.dart';
import 'package:flutterapp/chatapp/generatedandroidsmall1widget/generated/GeneratedShortsWidget1.dart';

/* Frame Android Small - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(33.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(33.0),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(33.0),
            child: Container(
              color: Color.fromARGB(255, 0, 0, 0),
            ),
          ),
          Positioned(
            left: -1.0,
            top: -4.0,
            right: null,
            bottom: null,
            width: 358.23809814453125,
            height: 33.00341796875,
            child: GeneratedAndroidStatusBarsWidget(),
          ),
          Positioned(
            left: 0.0,
            top: 29.0,
            right: null,
            bottom: null,
            width: 358.0,
            height: 70.0,
            child: GeneratedRectangle584Widget(),
          ),
          Positioned(
            left: 9.0,
            top: 34.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 26.99999237060547,
            child: GeneratedLogoWidget(),
          ),
          Positioned(
            left: 192.0,
            top: 34.0,
            right: null,
            bottom: null,
            width: 28.0,
            height: 28.0,
            child: GeneratedCastWidget(),
          ),
          Positioned(
            left: 244.0,
            top: 34.0,
            right: null,
            bottom: null,
            width: 28.0,
            height: 28.0,
            child: GeneratedNotifications_noneWidget(),
          ),
          Positioned(
            left: 288.0,
            top: 34.0,
            right: null,
            bottom: null,
            width: 28.0,
            height: 28.0,
            child: GeneratedSearchWidget(),
          ),
          Positioned(
            left: 327.0,
            top: 36.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedEllipse1Widget(),
          ),
          Positioned(
            left: -2.0,
            top: 92.0,
            right: null,
            bottom: null,
            width: 360.0,
            height: 480.0,
            child: GeneratedRectangle585Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.04446873664855957;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 16.008745193481445;

              double percentHeight = 0.031240051984786986;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 19.993633270263672;

              return Stack(children: [
                TransformHelper.translateAndScale(
                    translateX: constraints.maxWidth * 0.25,
                    translateY: constraints.maxHeight * 0.9125,
                    translateZ: 0,
                    scaleX: scaleX,
                    scaleY: scaleY,
                    scaleZ: 1,
                    child: GeneratedVectorWidget15())
              ]);
            }),
          ),
          Positioned(
            left: 17.0,
            top: 579.0,
            right: null,
            bottom: null,
            width: 325.0,
            height: 47.0,
            child: GeneratedGroup4Widget(),
          ),
          Positioned(
            left: 5.0,
            top: 640.0,
            right: null,
            bottom: null,
            width: 60.0,
            height: 3.0,
            child: GeneratedLine1Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 320.0,
            right: null,
            bottom: null,
            width: 364.0,
            height: 191.0,
            child: GeneratedRectangle596Widget(),
          ),
          Positioned(
            left: 7.0,
            top: 513.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 48.0,
            child: GeneratedEllipse11Widget(),
          ),
          Positioned(
            left: 289.0,
            top: 478.0,
            right: null,
            bottom: null,
            width: 67.0,
            height: 19.0,
            child: GeneratedRectangle596Widget1(),
          ),
          Positioned(
            left: 293.0,
            top: 478.0,
            right: null,
            bottom: null,
            width: 62.0,
            height: 20.0,
            child: Generated22023Widget(),
          ),
          Positioned(
            left: 41.0,
            top: 522.0,
            right: null,
            bottom: null,
            width: 290.0,
            height: 21.0,
            child: GeneratedTransformers2023HDTrailerInTamilWidget(),
          ),
          Positioned(
            left: 98.0,
            top: 537.0,
            right: null,
            bottom: null,
            width: 188.0,
            height: 18.0,
            child: Generated12MViews2hoursagoWidget(),
          ),
          Positioned(
            left: 61.0,
            top: 537.0,
            right: null,
            bottom: null,
            width: 55.0,
            height: 17.0,
            child: GeneratedMrBeastWidget(),
          ),
          Positioned(
            left: 336.0,
            top: 518.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedMore_vertWidget(),
          ),
          Positioned(
            left: -7.0,
            top: 105.0,
            right: null,
            bottom: null,
            width: 373.0,
            height: 215.0,
            child: GeneratedRectangle597Widget(),
          ),
          Positioned(
            left: 12.0,
            top: 120.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 24.839296340942383,
            child: GeneratedYoutubeshortsWidget(),
          ),
          Positioned(
            left: 45.0,
            top: 120.0,
            right: null,
            bottom: null,
            width: 53.0,
            height: 24.0,
            child: GeneratedShortsWidget1(),
          ),
          Positioned(
            left: 8.0,
            top: 150.0,
            right: null,
            bottom: null,
            width: 127.0,
            height: 155.0,
            child: GeneratedRectangle598Widget(),
          ),
          Positioned(
            left: 106.0,
            top: 162.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedMore_vertWidget1(),
          ),
          Positioned(
            left: 145.0,
            top: 150.0,
            right: null,
            bottom: null,
            width: 127.0,
            height: 155.0,
            child: GeneratedRectangle600Widget(),
          ),
          Positioned(
            left: 248.0,
            top: 162.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedMore_vertWidget2(),
          ),
          Positioned(
            left: 8.0,
            top: 287.0,
            right: null,
            bottom: null,
            width: 69.0,
            height: 17.0,
            child: Generated55MviewsWidget(),
          ),
          Positioned(
            left: 153.0,
            top: 287.0,
            right: null,
            bottom: null,
            width: 69.0,
            height: 17.0,
            child: Generated55MviewsWidget1(),
          ),
          Positioned(
            left: 280.0,
            top: 150.0,
            right: null,
            bottom: null,
            width: 80.0,
            height: 155.0,
            child: GeneratedRectangle599Widget(),
          ),
          Positioned(
            left: 292.0,
            top: 290.0,
            right: null,
            bottom: null,
            width: 71.0,
            height: 17.0,
            child: Generated33mViewsWidget(),
          ),
          Positioned(
            left: 6.0,
            top: 272.0,
            right: null,
            bottom: null,
            width: 133.0,
            height: 20.0,
            child: GeneratedViratKohliStatusWidget(),
          ),
          Positioned(
            left: 133.0,
            top: 274.0,
            right: null,
            bottom: null,
            width: 133.0,
            height: 20.0,
            child: GeneratedPSGStatusWidget(),
          ),
          Positioned(
            left: 276.0,
            top: 272.0,
            right: null,
            bottom: null,
            width: 128.0,
            height: 20.0,
            child: GeneratedPSGStatusWidget1(),
          ),
          Positioned(
            left: 9.0,
            top: 71.0,
            right: null,
            bottom: null,
            width: 49.0,
            height: 25.0,
            child: GeneratedRectangle596Widget2(),
          ),
          Positioned(
            left: 23.0,
            top: 76.0,
            right: null,
            bottom: null,
            width: 21.0,
            height: 20.0,
            child: GeneratedAllWidget(),
          ),
          Positioned(
            left: 75.0,
            top: 71.0,
            right: null,
            bottom: null,
            width: 79.0,
            height: 25.0,
            child: GeneratedRectangle596Widget3(),
          ),
          Positioned(
            left: 93.0,
            top: 76.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 20.0,
            child: GeneratedUIUXWidget(),
          ),
          Positioned(
            left: 165.0,
            top: 71.0,
            right: null,
            bottom: null,
            width: 93.0,
            height: 25.0,
            child: GeneratedRectangle596Widget4(),
          ),
          Positioned(
            left: 186.0,
            top: 76.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 20.0,
            child: GeneratedGamingWidget(),
          ),
          Positioned(
            left: 298.0,
            top: 76.0,
            right: null,
            bottom: null,
            width: 41.0,
            height: 20.0,
            child: GeneratedTodayWidget(),
          ),
          Positioned(
            left: 268.0,
            top: 72.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 25.0,
            child: GeneratedRectangle596Widget5(),
          ),
          Positioned(
            left: 276.0,
            top: 77.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 17.0,
            child: GeneratedWatchLaterWidget(),
          ),
          Positioned(
            left: 305.0,
            top: 574.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 34.0,
            child: GeneratedIcons8chatmessage481Widget(),
          )
        ]),
      ),
    ));
  }
}
